# https://docs.cnb.cool/zh/build/grammar.html#service-docker
"**":
  web_trigger_docker:
    - docker:
        image: docker.cnb.cool/gscore-mirror/docker-sync/astral-uv:python3.12-bookworm-slim
      imports: https://cnb.cool/gscore-mirror/keycode/-/blob/main/docker.io.yml
      services:
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      env:
        BASE_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        PLAYWRIGHT_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/playwright:latest
      stages:
        - name: cnb.cool lite
          script: docker buildx build --target lite -t ${BASE_IMAGE_TAG} --platform linux/amd64,linux/arm64 --push -f Dockerfile.base .

        - name: cnb.cool playwright
          script: docker buildx build --target playwright -t ${PLAYWRIGHT_IMAGE_TAG} --platform linux/amd64,linux/arm64 --push -f Dockerfile.playwright .

        - name: docker.io login
          script: docker login -u ${DOCKER_USER} -p "${DOCKER_PWD}" ${DOCKER_REGISTRY}

        - name: docker.io lite
          script: docker buildx build --target lite -t tyql688/gscore:latest --platform linux/amd64,linux/arm64 --push -f Dockerfile.base .

        - name: docker.io playwright
          script: docker buildx build --target playwright -t tyql688/gscore-playwright:latest --platform linux/amd64,linux/arm64 --push -f Dockerfile.playwright .
